### ISSUE TITLE
Processing widgets inside custom widgets

### ISSUE THREAD

**Issue by LouChiSoft** [fogarecious/iced_tutorial#6]
Hi, I have been following your tutorials to learn Iced. I really appreciate the sections on custom widgets. I have been using them to try implement a custom title bar for my window. 

In modifying the code so that the button I pass in closes the window I have found that any button passed into the custom widget isn't emmiting messages. The button works just fine if I don't have it wrapped in my custom widget. Is there something I am missing from the guides to get those buttons working?

I thought maybe I needed to handle on_event. So I just added a simple implementation of it that return `event::Status::Ignored` because I would have thought that would have meant that the event is passed onto the child widget. But that doesn't seem to have made it work either.

I don't suppose you konw what I am doing wrong?

**Comment by LouChiSoft** [comment]
Figured it out. I needed to call on_event for the child widget from within the custom widget's on_event function.

**Comment by fogarecious** [comment]
Thank you for pointing out this issue. I have added a remark in Widgets With Children to mention how to pass events from outer widgets to inner widgets. (See #11 )
