### ISSUE TITLE
Should iced::Renderer<Self::Theme> be modified?

### ISSUE THREAD

**Issue by Initsnow** [fogarecious/iced_tutorial#8]
Now that I'm using iced version 0.12.1, it seems like `iced::Renderer<Self::Theme>` should be replaced by `Self::Theme,iced::Renderer`.
If I don't replace it will compile error

**Comment by Initsnow** [comment]
well, I submitted pr

**Comment by fogarecious** [comment]
I think we can use the following:
```rust
fn view(&self) -> iced::Element<Self::Message>
```
It is simpler and clearer.
I will update the tutorial later.
